build:
    environment:
        nodes:
            php72:
                environment:
                    php: 7.2
            php73:
                environment:
                    php: 7.3
            php74:
                environment:
                    php: 7.4
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
