checks:
    php:
        code_rating: true
        duplication: true
build:
    nodes:
        php72:
            environment:
                php: 7.2
        php73:
            environment:
                php: 7.3
        php74:
            environment:
                php: 7.4
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        test: true
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
