version: 2.1

jobs:
    build:
        docker:
            - image: circleci/php:7.2
        steps:
            - checkout
            - run: composer install
    test:
        docker:
            - image: circleci/php:7.2
        steps:
            - checkout
            - run: vendor/bin/phpunit

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test:
                requires:
                  - build